name: VocalAscend
options:
  bundleIdPrefix: com.vocalascend
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  VocalAscend:
    type: application
    platform: iOS
    sources:
      - path: VocalAscend
        excludes:
          - "**/.DS_Store"
    resources:
      - path: VocalAscend/Resources
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: VocalAscend/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vocalascend.app
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: VocalAscend/Info.plist
      properties:
        CFBundleDisplayName: Vocal Ascend
        CFBundleName: VocalAscend
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSMicrophoneUsageDescription: "Vocal Ascend needs microphone access to detect your pitch and provide real-time feedback on your singing."
        UIUserInterfaceStyle: Automatic
    entitlements:
      path: VocalAscend/VocalAscend.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true

  VocalAscendTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VocalAscendTests
    dependencies:
      - target: VocalAscend
    settings:
      base:
        INFOPLIST_FILE: VocalAscendTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vocalascend.app.tests
